"""
Main script to populate the CLARISA institutions table in Supabase with embeddings generated by Amazon Titan
"""
import sys
from tqdm import tqdm
from logger.logger_util import get_logger
from src.clarisa_api import get_all_parsed_institutions
from src.embeddings import get_embedding, embedding_to_list
from src.supabase_client import insert_institutions_batch, count_institutions

logger = get_logger()


def generate_embeddings_for_institution(institution):
    """
    Generates embeddings for the name and acronym of an institution
    
    Args:
        institution: Dictionary with institution data
        
    Returns:
        Dict: Institution with added embeddings
    """
    name = institution.get('name', '')
    acronym = institution.get('acronym', '')
    
    if name:
        name_embedding = get_embedding(name)
        institution['name_embedding'] = embedding_to_list(name_embedding)
    else:
        institution['name_embedding'] = None
    
    if acronym:
        acronym_embedding = get_embedding(acronym)
        institution['acronym_embedding'] = embedding_to_list(acronym_embedding)
    else:
        institution['acronym_embedding'] = None
    
    return institution


def populate_clarisa_institutions(batch_size=50):
    """
    Main process to populate the CLARISA institutions table
    
    Args:
        batch_size: Size of each batch for insertion
    """
    logger.info("🚀 Starting population of CLARISA_INSTITUTIONS_V2 table")
    logger.info("📋 STEP 1: Fetching institutions from CLARISA...")
    institutions = get_all_parsed_institutions()
    
    if not institutions:
        logger.error("❌ Failed to fetch institutions from CLARISA. Aborting.")
        sys.exit(1)
    
    logger.info(f"✅ {len(institutions)} institutions fetched and parsed")
    
    logger.info("🧠 STEP 2: Generating embeddings with Amazon Titan...")
    logger.info(f"   This may take several minutes for {len(institutions)} institutions...")
    
    institutions_with_embeddings = []
    
    for institution in tqdm(institutions, desc="Generating embeddings"):
        try:
            inst_with_emb = generate_embeddings_for_institution(institution)
            institutions_with_embeddings.append(inst_with_emb)
        except Exception as e:
            logger.warning(f"⚠️  Error processing institution {institution.get('clarisa_id')}: {e}")
            continue
    
    logger.info(f"✅ Embeddings generated for {len(institutions_with_embeddings)} institutions")
    
    logger.info("💾 STEP 3: Inserting institutions into Supabase...")
    stats = insert_institutions_batch(institutions_with_embeddings, batch_size=batch_size)
    
    logger.info("=" * 30)
    logger.info("📊 INSERTION SUMMARY")
    logger.info("=" * 30)
    logger.info(f"✅ Successful: {stats['success']}")
    logger.info(f"❌ Failed:  {stats['failed']}")
    
    total_in_db = count_institutions()
    logger.info(f"📈 Total institutions in the database: {total_in_db}")
    logger.info("✅ Process completed successfully!")


def main():
    """Main function"""
    current_count = count_institutions()
    logger.info(f"📊 Current institutions in the database: {current_count}")
    
    if current_count > 0:
        response = input("⚠️  The table already contains data. Do you want to continue? (y/n): ")
        if response.lower() != 'y':
            logger.info("❌ Operation cancelled by the user")
            sys.exit(0)
    
    populate_clarisa_institutions(batch_size=50)


if __name__ == "__main__":
    main()