"""
Main script to populate the CLARISA institutions table in Supabase with embeddings generated by Amazon Titan
"""
import sys
import hashlib
import json
import argparse
from tqdm import tqdm
from typing import Dict, List, Tuple
from logger.logger_util import get_logger
from src.clarisa_api import get_all_parsed_institutions
from src.embeddings import get_embedding, embedding_to_list
from src.supabase_client import (
    insert_institutions_batch, 
    count_institutions,
    get_all_institutions_from_db,
    get_all_clarisa_ids_from_db,
    delete_institutions_by_ids,
    clear_all_cache
)

logger = get_logger()


def generate_embeddings_for_institution(institution):
    """
    Generates embeddings for the name and acronym of an institution
    
    Args:
        institution: Dictionary with institution data
        
    Returns:
        Dict: Institution with added embeddings
    """
    name = institution.get('name', '')
    acronym = institution.get('acronym', '')
    
    if name:
        name_embedding = get_embedding(name)
        institution['name_embedding'] = embedding_to_list(name_embedding)
    else:
        institution['name_embedding'] = None
    
    if acronym:
        acronym_embedding = get_embedding(acronym)
        institution['acronym_embedding'] = embedding_to_list(acronym_embedding)
    else:
        institution['acronym_embedding'] = None
    
    return institution


def calculate_institution_hash(institution: Dict) -> str:
    """
    Calculates a hash of the relevant institution data to detect changes
    
    Args:
        institution: Dictionary with institution data
        
    Returns:
        str: MD5 hash of the institution's relevant data
    """
    # Only hash the fields that would require re-embedding if changed
    relevant_data = {
        'name': institution.get('name', ''),
        'acronym': institution.get('acronym', ''),
        'website': institution.get('website', ''),
        'countries': sorted(institution.get('countries', [])),  # Sort for consistency
        'institution_type': institution.get('institution_type', '')
    }
    
    # Create a stable JSON representation
    data_str = json.dumps(relevant_data, sort_keys=True)
    
    # Return MD5 hash
    return hashlib.md5(data_str.encode('utf-8')).hexdigest()


def populate_clarisa_institutions(batch_size=50):
    """
    Main process to populate the CLARISA institutions table
    
    Args:
        batch_size: Size of each batch for insertion
    """
    logger.info("🚀 Starting population of CLARISA_INSTITUTIONS_V2 table")
    logger.info("📋 STEP 1: Fetching institutions from CLARISA...")
    institutions = get_all_parsed_institutions()
    
    if not institutions:
        logger.error("❌ Failed to fetch institutions from CLARISA. Aborting.")
        sys.exit(1)
    
    logger.info(f"✅ {len(institutions)} institutions fetched and parsed")
    
    logger.info("🧠 STEP 2: Generating embeddings with Amazon Titan...")
    logger.info(f"   This may take several minutes for {len(institutions)} institutions...")
    
    institutions_with_embeddings = []
    
    for institution in tqdm(institutions, desc="Generating embeddings"):
        try:
            inst_with_emb = generate_embeddings_for_institution(institution)
            institutions_with_embeddings.append(inst_with_emb)
        except Exception as e:
            logger.warning(f"⚠️  Error processing institution {institution.get('clarisa_id')}: {e}")
            continue
    
    logger.info(f"✅ Embeddings generated for {len(institutions_with_embeddings)} institutions")
    
    logger.info("💾 STEP 3: Inserting institutions into Supabase...")
    stats = insert_institutions_batch(institutions_with_embeddings, batch_size=batch_size)
    
    logger.info("=" * 30)
    logger.info("📊 INSERTION SUMMARY")
    logger.info("=" * 30)
    logger.info(f"✅ Successful: {stats['success']}")
    logger.info(f"❌ Failed:  {stats['failed']}")
    
    total_in_db = count_institutions()
    logger.info(f"📈 Total institutions in the database: {total_in_db}")
    logger.info("✅ Process completed successfully!")


def sync_clarisa_institutions(batch_size: int = 50, delete_obsolete: bool = False) -> Dict[str, int]:
    """
    Synchronizes CLARISA institutions with the database incrementally
    Only processes new or modified institutions to save time and resources
    
    Args:
        batch_size: Size of each batch for insertion
        delete_obsolete: Whether to delete institutions that no longer exist in CLARISA
        
    Returns:
        Dict: Statistics about the sync operation
    """
    logger.info("🔄 Starting INCREMENTAL SYNC of CLARISA institutions")
    
    # Step 1: Fetch current institutions from CLARISA
    logger.info("📋 STEP 1: Fetching institutions from CLARISA...")
    clarisa_institutions = get_all_parsed_institutions()
    
    if not clarisa_institutions:
        logger.error("❌ Failed to fetch institutions from CLARISA. Aborting.")
        return {'new': 0, 'modified': 0, 'obsolete': 0, 'unchanged': 0, 'failed': 0}
    
    logger.info(f"✅ {len(clarisa_institutions)} institutions fetched from CLARISA")
    
    # Step 2: Fetch existing institutions from database
    logger.info("💾 STEP 2: Fetching existing institutions from database...")
    db_institutions = get_all_institutions_from_db()
    logger.info(f"✅ {len(db_institutions)} institutions in database")
    
    # Create lookup dictionaries
    clarisa_dict = {inst['clarisa_id']: inst for inst in clarisa_institutions}
    db_dict = {inst['clarisa_id']: inst for inst in db_institutions}
    
    clarisa_ids = set(clarisa_dict.keys())
    db_ids = set(db_dict.keys())
    
    # Step 3: Identify what needs to be processed
    logger.info("🔍 STEP 3: Analyzing differences...")
    
    new_ids = clarisa_ids - db_ids
    obsolete_ids = db_ids - clarisa_ids
    potentially_modified_ids = clarisa_ids & db_ids
    
    logger.info(f"   📊 New institutions: {len(new_ids)}")
    logger.info(f"   📊 Potentially modified: {len(potentially_modified_ids)}")
    logger.info(f"   📊 Obsolete institutions: {len(obsolete_ids)}")
    
    # Identify truly modified institutions by comparing hashes
    modified_ids = set()
    unchanged_count = 0
    
    if potentially_modified_ids:
        logger.info("   🔎 Checking for actual modifications...")
        for inst_id in potentially_modified_ids:
            clarisa_hash = calculate_institution_hash(clarisa_dict[inst_id])
            db_hash = calculate_institution_hash(db_dict[inst_id])
            
            if clarisa_hash != db_hash:
                modified_ids.add(inst_id)
            else:
                unchanged_count += 1
        
        logger.info(f"   ✅ Actually modified: {len(modified_ids)}")
        logger.info(f"   ✅ Unchanged: {unchanged_count}")
    
    # Step 4: Process new and modified institutions
    institutions_to_process = []
    
    for inst_id in new_ids:
        institutions_to_process.append(clarisa_dict[inst_id])
    
    for inst_id in modified_ids:
        institutions_to_process.append(clarisa_dict[inst_id])
    
    total_to_process = len(institutions_to_process)
    
    if total_to_process == 0:
        logger.info("✅ No new or modified institutions to process!")
    else:
        logger.info(f"🧠 STEP 4: Generating embeddings for {total_to_process} institutions...")
        
        institutions_with_embeddings = []
        failed_count = 0
        
        for institution in tqdm(institutions_to_process, desc="Generating embeddings"):
            try:
                inst_with_emb = generate_embeddings_for_institution(institution)
                institutions_with_embeddings.append(inst_with_emb)
            except Exception as e:
                logger.warning(f"⚠️  Error processing institution {institution.get('clarisa_id')}: {e}")
                failed_count += 1
                continue
        
        logger.info(f"✅ Embeddings generated for {len(institutions_with_embeddings)} institutions")
        
        # Step 5: Insert/Update in database
        logger.info("💾 STEP 5: Upserting institutions into Supabase...")
        insert_stats = insert_institutions_batch(institutions_with_embeddings, batch_size=batch_size)
        logger.info(f"✅ Upserted {insert_stats['success']} institutions")
        
        if insert_stats['failed'] > 0:
            logger.warning(f"⚠️  Failed to upsert {insert_stats['failed']} institutions")
    
    # Step 6: Handle obsolete institutions
    deleted_count = 0
    if obsolete_ids and delete_obsolete:
        logger.info(f"🗑️  STEP 6: Deleting {len(obsolete_ids)} obsolete institutions...")
        deleted_count = delete_institutions_by_ids(list(obsolete_ids))
    elif obsolete_ids:
        logger.info(f"⚠️  NOTE: {len(obsolete_ids)} obsolete institutions found but not deleted (use --delete-obsolete to remove)")
    
    # Step 7: Invalidate cache if database changed
    cache_cleared = 0
    if len(new_ids) > 0 or len(modified_ids) > 0:
        logger.info("🗑️  STEP 7: CLARISA database changed - Invalidating cache...")
        cache_cleared = clear_all_cache()
        logger.info(f"✅ Cache invalidated to ensure fresh matches with updated data")
    else:
        logger.info("✅ No changes detected - Cache remains valid")
    
    # Final summary
    logger.info("=" * 50)
    logger.info("📊 SYNC SUMMARY")
    logger.info("=" * 50)
    logger.info(f"   🆕 New institutions: {len(new_ids)}")
    logger.info(f"   ✏️  Modified institutions: {len(modified_ids)}")
    logger.info(f"   ✅ Unchanged institutions: {unchanged_count}")
    logger.info(f"   🗑️  Obsolete institutions: {len(obsolete_ids)} {'(deleted)' if delete_obsolete else '(kept)'}")
    
    total_in_db = count_institutions()
    logger.info(f"   📈 Total institutions in database: {total_in_db}")
    logger.info("✅ Sync completed successfully!")
    
    return {
        'new': len(new_ids),
        'modified': len(modified_ids),
        'obsolete': len(obsolete_ids),
        'unchanged': unchanged_count,
        'deleted': deleted_count,
        'failed': failed_count if total_to_process > 0 else 0,
        'cache_cleared': cache_cleared
    }


def main():
    """Main function with command-line argument support"""
    parser = argparse.ArgumentParser(
        description='Populate or sync CLARISA institutions in Supabase',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Initial population (full load)
  python -m src.populate_clarisa_db --mode populate
  
  # Incremental sync (only new/modified)
  python -m src.populate_clarisa_db --mode sync
  
  # Sync and delete obsolete institutions
  python -m src.populate_clarisa_db --mode sync --delete-obsolete
        """
    )
    
    parser.add_argument(
        '--mode',
        choices=['populate', 'sync'],
        default='populate',
        help='Operation mode: "populate" for full load, "sync" for incremental sync (default: populate)'
    )
    
    parser.add_argument(
        '--batch-size',
        type=int,
        default=50,
        help='Batch size for database operations (default: 50)'
    )
    
    parser.add_argument(
        '--delete-obsolete',
        action='store_true',
        help='Delete institutions that no longer exist in CLARISA (only for sync mode)'
    )
    
    parser.add_argument(
        '--force',
        action='store_true',
        help='Skip confirmation prompts'
    )
    
    args = parser.parse_args()
    
    current_count = count_institutions()
    logger.info(f"📊 Current institutions in the database: {current_count}")
    
    if args.mode == 'populate':
        # Full population mode
        logger.info("📋 Mode: FULL POPULATION")
        
        if current_count > 0 and not args.force:
            response = input("⚠️  The table already contains data. Do you want to continue? (y/n): ")
            if response.lower() != 'y':
                logger.info("❌ Operation cancelled by the user")
                sys.exit(0)
        
        populate_clarisa_institutions(batch_size=args.batch_size)
    
    elif args.mode == 'sync':
        # Incremental sync mode
        logger.info("🔄 Mode: INCREMENTAL SYNC")
        
        if current_count == 0:
            logger.warning("⚠️  Database is empty. Consider using --mode populate for initial load.")
            if not args.force:
                response = input("Continue with sync anyway? (y/n): ")
                if response.lower() != 'y':
                    logger.info("❌ Operation cancelled by the user")
                    sys.exit(0)
        
        sync_clarisa_institutions(
            batch_size=args.batch_size,
            delete_obsolete=args.delete_obsolete
        )


if __name__ == "__main__":
    main()