"""Registry of the prompts managed through the STAR Prompt Manager.

Each entry is keyed by a prompt ID (the service or module name) and holds the
default section text plus the template variables that section text may reference.

Adding a new prompt here is all it takes to expose it through /api/prompts: the
GET seeds missing S3 records from these defaults, so there is no manual step.
"""

from ai.prompts.prompt_document_overview import DEFAULT_PROMPT_DOCUMENT_OVERVIEW

PROJECT_OVERVIEW_PROMPT_ID = "project-overview"

# Section keys, in the order they are assembled into the final prompt.
PROMPT_SECTIONS = (
    "system_role",
    "context",
    "user_instructions",
    "expected_output_format",
)


class PromptVariable:
    """A `{placeholder}` the service replaces with real context at generation time."""

    def __init__(self, name: str, description: str, required: bool = True):
        self.name = name
        self.description = description
        self.required = required

    @property
    def placeholder(self) -> str:
        return "{" + self.name + "}"

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "placeholder": self.placeholder,
            "description": self.description,
            "required": self.required,
        }


PROJECT_OVERVIEW_VARIABLES = (
    PromptVariable(
        name="available_context_sources",
        description=(
            "Numbered list of the context sources actually present in the request. "
            "Generated by the service for each request."
        ),
    ),
    PromptVariable(
        name="project_information",
        description=(
            "STAR project metadata: description, donor, unit and SDGs. Replaced with a "
            "'not available' note when STAR returns nothing."
        ),
    ),
    PromptVariable(
        name="project_results",
        description=(
            "Metadata about the results reported for the project in STAR. Replaced with a "
            "'not available' note when STAR returns nothing."
        ),
    ),
    PromptVariable(
        name="uploaded_evidence",
        description=(
            "Text extracted from the documents uploaded as project evidence, separated per "
            "file. Replaced with a note when no documents were uploaded."
        ),
    ),
    PromptVariable(
        name="user_input",
        description=(
            "Free-text input typed by the user for this overview. Replaced with a note when "
            "no text was provided."
        ),
    ),
)


PROMPT_REGISTRY = {
    PROJECT_OVERVIEW_PROMPT_ID: {
        "name": "Project Overview",
        "description": (
            "Prompt used to synthesize a structured project overview from STAR project "
            "metadata, reported results and uploaded evidence."
        ),
        "defaults": DEFAULT_PROMPT_DOCUMENT_OVERVIEW,
        "variables": PROJECT_OVERVIEW_VARIABLES,
    },
}


def is_known_prompt_id(prompt_id: str) -> bool:
    return prompt_id in PROMPT_REGISTRY


def known_prompt_ids() -> list[str]:
    return sorted(PROMPT_REGISTRY)


def get_prompt_definition(prompt_id: str) -> dict:
    """Return the registry entry for a prompt ID.

    Raises:
        ValueError: If the prompt ID is not registered.
    """
    definition = PROMPT_REGISTRY.get(prompt_id)
    if definition is None:
        raise ValueError(
            f"Unknown prompt id '{prompt_id}'. Known ids: {', '.join(known_prompt_ids())}"
        )
    return definition


def get_default_sections(prompt_id: str) -> dict[str, str]:
    """Copy of the code-defined default sections for a prompt ID."""
    return dict(get_prompt_definition(prompt_id)["defaults"])


def get_variables(prompt_id: str) -> tuple[PromptVariable, ...]:
    return get_prompt_definition(prompt_id)["variables"]
