[project]
name = "ai-insights-service"
version = "0.1.0"
description = "LLM-based microservice for document analysis and insight generation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3",
    "numpy",
    "pandas",
    "openpyxl",
    "tqdm",
    "python-dotenv",
    "pyjwt",
    "aiohttp",
    "certifi",
    "requests",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "mangum",
    "pydantic",
    "mammoth",
    "python-pptx",
    "httpx",
]
