"""Pydantic models for Fast Response API."""

from pydantic import BaseModel, Field

class FastRequest(BaseModel):
    """
    Request model for generating a fast response.
    """
    prompt: str = Field(
        ...,
        description="Instruction for the LLM (e.g., 'Summarize the text', 'Improve the writing', etc.)",
        examples=["Summarize the following text in 3 lines.", "Improve the writing of the following paragraph."]
    )
    input_text: str = Field(
        ...,
        description="Text to apply the prompt to.",
        examples=["Sustainable agriculture is key for rural development..."]
    )

class FastResponse(BaseModel):
    """
    Successful response model for Fast Response API.
    """
    prompt: str = Field(..., description="Received prompt", examples=["Summarize the following text in 3 lines."])
    input_text: str = Field(..., description="Received input text", examples=["Sustainable agriculture is key for rural development..."])
    output: str = Field(..., description="Response generated by the LLM", examples=["Sustainable agriculture drives rural development..."])
    status: str = Field(default="success", description="Response status indicator", examples=["success"])

class ErrorResponse(BaseModel):
    """
    Error response model for Fast Response API.
    """
    error: str = Field(..., description="Short error message", examples=["Invalid parameters", "Internal error"])
    status: str = Field(default="error", description="Error status indicator", examples=["error"])
    details: str | None = Field(None, description="Additional error details")